/** 
 * This file generated by Apso.
*//* eslint @typescript-eslint/no-unused-vars: "off" */

import {
    Column,
    Entity,
ManyToOne,
OneToOne,    PrimaryGeneratedColumn,
    Generated,
    JoinColumn,
    JoinTable,
    Index,
    Unique,
    PrimaryColumn
} from "typeorm";
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';
import {Menu} from '../Menu/Menu.entity';
import {Table} from '../Table/Table.entity';
import {Payment} from '../Payment/Payment.entity';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('order')
export class Order {
    // Fields
    @PrimaryGeneratedColumn()
    id!: number;





@Column({ "type": "int" })

table_id: number;


@IsOptional({ groups: [UPDATE] })
@IsNotEmpty({ groups: [CREATE] })
@Column({ type: "varchar", length: 255, nullable: false  })

status: string; 

// Associations    
                    @ManyToOne(() => Menu, menu => menu.orders)
        @JoinColumn({ name: 'menuId' })
        menu: Menu
        @Column({ type: "integer", })
        menuId: number;
    
                        @ManyToOne(() => Table, table => table.orders)
        @JoinColumn({ name: 'tableId' })
        table: Table
        @Column({ type: "integer", })
        tableId: number;
    
            
        @OneToOne(
            (type: any) => Payment,
                        {
                onDelete: "CASCADE",
                cascade: ["insert", "update"],
            })
        @JoinColumn()
        payment: Payment
    }