/** 
 * This file generated by Apso.
*/
import {MenuModule} from './Menu/Menu.module'
import {TableModule} from './Table/Table.module'
import {OrderModule} from './Order/Order.module'
import {PaymentModule} from './Payment/Payment.module'

export default [
MenuModule,
TableModule,
OrderModule,
PaymentModule,
]