import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class OrderCreate {
  @ApiProperty()
  table_id: number;
  @ApiProperty()
  status: string;
}

export class Order {
  @ApiProperty()
  id: number;
  @ApiProperty()
  table_id: number;
  @ApiProperty()
  status: string;
}
