import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PaymentCreate {
  @ApiProperty()
  order_id: number;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  payment_date: Date;
}

export class Payment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  order_id: number;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  payment_date: Date;
}
