/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Table } from './Table.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TableService } from './Table.service';
import { TableController } from './Table.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Table])],
  providers: [TableService],
  exports: [TableService],
  controllers: [TableController],
})
export class TableModule {}
