import { ApiProperty } from '@nestjs/swagger';
/** 
 * This file generated by Apso.
*/

export class TableCreate {
    @ApiProperty()
      number: number;
      @ApiProperty()
      capacity: number;
      @ApiProperty()
      status: string;
  };

export class Table {
    @ApiProperty()
    id: number;
    @ApiProperty()
      number: number;
      @ApiProperty()
      capacity: number;
      @ApiProperty()
      status: string;
  };