import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class TableCreate {
  @ApiProperty()
  number: string;
  @ApiProperty()
  capacity: string;
  @ApiProperty()
  status: string;
}

export class Table {
  @ApiProperty()
  id: number;
  @ApiProperty()
  number: string;
  @ApiProperty()
  capacity: string;
  @ApiProperty()
  status: string;
}
