import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class MenuCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  category: string;
}

export class Menu {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  category: string;
}
